[project]
requires-python = "==3.12"

[tool.pytest.ini_options]
testpaths = "_*"
addopts = "--ff --ruff --ruff-format"
norecursedirs = "_build _static _templates"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
