# Currently this file is used merely for configuration
# of tools. For dependencies, see requirements.txt.
#
# One day there will be a way how to specify dependencies
# in pyproject.toml, and then install them by pip without
# the need for installing this directory as a package
# on its own, but that day is not today.

[project]
requires-python = "==3.12"

[tool.pytest.ini_options]
testpaths = "_*"
addopts = "--ff --ruff --ruff-format"
norecursedirs = "_build _static _templates"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
